[package]
name = "yapping_core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "=0.4.38"
serde = { version = "1.0.210", features = ["derive"] }
bincode = "=1.3.3"
l3gion_rust = { git = "https://github.com/Cunha-Renato/l3gion_rust" }